baseURL: /
languageCode: en-us
title: Francisco Cardozo
paginate: 3
theme: maverick
permalinks:
  pages: /:slug
params:
  author: Francisco Cardozo
  comments:
    githubRepo: focardozom/webpage
    theme: github-light
  description: personal webpage
  logo: /assets/favicon.ico
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: '-110'
    - identifier: posts
      name: Post
      url: /posts/
      weight: -200
markup:
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    anchorLineNos: no
    codeFences: yes
    guessSyntax: no
    hl_Lines: ''
    hl_inline: no
    lineAnchors: ''
    lineNoStart: 1
    lineNos: no
    lineNumbersInTable: yes
    noClasses: yes
    noHl: no
    style: monokailight
    tabWidth: 4
taxonomies:
  tag: tags
outputs:
  home:
    - HTML
    - RSS
    - JSON
  section: HTML
outputFormats:
  JSON:
    baseName: feed
    ignoreErrors: error-remote-getjson
    mediatype: application/json
  RSS:
    baseName: atom
    mediatype: application/rss
