---
title: "Maximizing the Impact of Your R Teaching: Insights from Garrett Grolemund"
author: "Francisco Cardozo"
date: 2023-02-10
categories: ["Teaching"]
tags: ["POSIT", "YouTube", "Learning"]
---

I recently watched a presentation by Garrett Grolemund, the Director of Learning at Rstudio, on the POSIT Enterprise Community Meetup on YouTube. I wanted to share with you some of the interesting thoughts about teaching R that he mentioned.

<iframe src="https://www.youtube.com/embed/ElO5gDCG3X8?start=19" width="100%" height="360" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>


# Notes

## Context

* Garret believes that the success of the training ultimately depends on how it's delivered. 
* Teachers out there really aren't that good and online courses are not so great. 
* People who become experts in R by years of practice. However, they may not have had the opportunity to devote those years to being a good teacher.
* There is  theories in psychology(such as cognitive load theory and multimedia learning theory) that can be applied to make training more successful.
* Research shows that students only retain about 56% of the content from a lecture
* The retention rate decreases over time. 
* Studies on procedural instruction show similar results, with only 60% of students able to reproduce the procedure immediately after training.
* Six months later, the number drops to 40%, and a year later it drops to 30%
* Training outcomes are not always great and this is a "dirty secret" of the training industry.
* Trainers are not always trained to be trainers, which is a challenge in the field.
* Education is not simply about transferring information from an educator to a student, and the student then becoming an expert.

## Insights 

### Practice

* The more the task is practiced, the more the brain will conserve the neural networks and retain the ability to perform the task. This is not likely to occur in a workshop that lasts only half a day or two days. 
* To build a robust neural network, it is important to sleep. 
* The ability to perform a new skill in six months from now dependent on the amount of practice they receive after initial instruction, rather than the instruction itself.

> "Well, the revelation we had at our studio is that data science is a skill, and if you
want to learn to do good data science with code or otherwise, you have to practice it
and learn it as a skill."

### Mentors, Mates and Accountability 

* As a student, it is possible to practice a skill incorrectly without even being aware of it. To practice effectively and efficiently, it is crucial to receive feedback and guidance to make sure the proper techniques are being utilized.
* Individuals do not acquire knowledge in a vacuum, they are driven by social influences and the identity they construct by participating in a community that is studying data science.
* The lacking factor in online courses is motivation, which can be obtained through interaction with a mentor or peers. Talking to them can provide the necessary inspiration.
* Having a mentor or being part of a group provides accountability, as one is expected to show up with something to demonstrate to them.

> "So, as you go through the course, not only do you have an expert who has your back who's coaching you, you also have fellow travelers who you could discuss things with.
You could work through problems together and, you might not even realize it, but you can
hold each other accountable and motivated as you go through the process."

### Recomendations

* *How Learning Happens* by Paul Kirschner and Carl. [link to amazon. But also consult with your librarian friend]( Hedentrick.(https://www.amazon.com/How-Learning-Happens-Paul-Kirschner/dp/0367184575))

* [Visit Posit Academy](https://posit.co/products/enterprise/academy/). You can learn in detail about the POSIT Academy model in minute 24.

